version: "2"

run:
  go: "1.25"
  timeout: 2m

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
  # errcheck disabled for v0.1: existing code has many unchecked
  # fmt.Fprintf/defer .Close() calls. Enable after adding nolint annotations.
  disable:
    - errcheck

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
  max-issues-per-linter: 50
  max-same-issues: 5
