name: Bug report
description: Report a bug or unexpected behaviour
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Run `omnisess ...`
        2. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected-actual
    attributes:
      label: Expected vs. actual behaviour
      description: What did you expect to happen? What happened instead?
    validations:
      required: true
  - type: input
    id: os-go-version
    attributes:
      label: OS and Go version
      description: "e.g. macOS 14, Go 1.22"
    validations:
      required: true
  - type: input
    id: omnisess-version
    attributes:
      label: omnisess version
      description: "Run `omnisess` and note the version from the build source or git commit hash."
    validations:
      required: true
